import { Toaster } from '@/components/ui/toaster'
import Header from '@/containers/Header'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'
import { Inter } from 'next/font/google'
import TanstackProvider from '../provider/tanstack-query-provider'
import { ThemeProvider } from '../provider/theme-provider'
import './globals.css'
import { locales } from '@/i18n'


const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  unstable_setRequestLocale(locale);
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} className="scroll-smooth antialiased" suppressHydrationWarning={true}>
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <NextIntlClientProvider messages={messages} >
          <ThemeProvider
            attribute='class'
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TanstackProvider>
              <Header />
              <main className="grow" >
                {children}
              </main>
              <Toaster />
            </TanstackProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
